global using AutoMapper;
global using MediatR;
global using System.Runtime.Serialization;
global using WMS.Application.DTOs.PartyDTOs;
global using WMS.Application.ErrorNotifications.ErrorDetails;
global using WMS.Application.Exceptions;
global using WMS.Domain.AggregateModels.PartyAggregate;
global using WMS.Domain.Enum;
global using WMS.Domain.InterfaceRepositories.IParty;
